### ISSUE TITLE
NaNaNaNa appearing for multiple dates fields

### ISSUE THREAD

**Issue by nastynoel** [Cadasta/cadasta#2]
Several dates fields are still showing NaNaNaNa instead of correct and valid dates values. See the attachment for screengrabs of these instances. They relate to DOB for parties and date acquired for relatioships. 
[Issues screen grabs.docx](https://github.com/Cadasta/cadasta/files/127470/Issues.screen.grabs.docx)

**Comment by wonderchook** [comment]
Fixed: https://github.com/Cadasta/ckanext-project/issues/162

**Comment by ian-ross** [comment]
Some background for this: in Chrome, you get this:

```
> var d = new Date("2011-02-07T11:05:00");
undefined
> d
Mon Feb 07 2011 12:05:00 GMT+0100 (CET)
> var d = new Date("2011-02-07 11:05:00");
undefined
> d
Mon Feb 07 2011 11:05:00 GMT+0100 (CET)
```

In Firefox:

```
> var d = new Date("2011-02-07T11:05:00");
undefined
> d
Date 2011-02-07T10:05:00.000Z
> var d = new Date("2011-02-07 11:05:00");
undefined
> d
Invalid Date
```

And some relevant links:

http://stackoverflow.com/questions/11368361/how-can-i-parse-this-date-string-consistently-across-browsers#11368479
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse?redirectlocale=en-US&redirectslug=JavaScript%2FReference%2FGlobal_Objects%2FDate%2Fparse
http://dygraphs.com/date-formats.html

It's not pretty, but I think changes localised to [here](https://github.com/Cadasta/ckanext-project/blob/master/ckanext/project/public/shared/src/services/utilityService.js#L10-L47) ought to fix it.  Maybe even just changing the `replace(/T/, ' ')` to `replace(/ /, 'T')` might be enough.
