### ISSUE TITLE
Update icon on tab for CKAN platform

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta#4]
@nastynoel commented on [Wed May 18 2016](https://github.com/Cadasta/cadasta-platform/issues/201)

Need to add Cadasta icon to tab header for platform.cadasta.org as was done for demo.cadasta.org

---

@wonderchook commented on [Thu May 19 2016](https://github.com/Cadasta/cadasta-platform/issues/201#issuecomment-220370637)

@bjohare is this something you updated recently on the demo site?

**Comment by bjohare** [comment]
@wonderchook yes, updated page title and favicon on demo. Updated title on platform first but didn't realize there was a favicon available when I did it. Favicon display requires apache restart but platform is currently in use so was planning to leave this until after 20th May.

**Comment by bjohare** [comment]
done.

**Comment by amplifi** [comment]
I think it's safe to close this one 👍
